Feature/apply if and apply if async operators
PGS-dev/rxjs-x-operators pull request #6
Opened 2019-09-07 07:11 UTC by jakub-hajduk

2019-09-07 07:13 UTC, jakub-hajduk commented
there is also another one - toggle status.

2019-09-09 07:54 UTC, dbojarski requested changes

2019-09-09 07:54 UTC, dbojarski commented on apply-if-async/apply-if-async-operator.spec.ts
> +  // it('should apply given elseOperators if given observable returned false.', () => {
remove please

2019-09-09 07:54 UTC, dbojarski commented on apply-if-async/apply-if-async.operator.ts
> +        // @ts-ignore
remove or add tslint fle

2019-09-09 07:54 UTC, dbojarski commented on toggle-status/toggle-status-operator.spec.ts
> +    .pipe(
format

2019-09-18 18:20 UTC, merged